"""add_is_auto_is_cuti_to_holidays

Revision ID: 92057ab12916
Revises: 001
Create Date: 2025-12-22 07:16:50.170106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92057ab12916'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('is_auto', sa.Boolean(), nullable=True))
    op.add_column('holidays', sa.Column('is_cuti', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'is_cuti')
    op.drop_column('holidays', 'is_auto')
    # ### end Alembic commands ###
