"""add_is_excluded_to_holidays

Revision ID: 99ee100d1693
Revises: 92057ab12916
Create Date: 2025-12-22 07:33:52.817097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ee100d1693'
down_revision: Union[str, None] = '92057ab12916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('is_excluded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'is_excluded')
    # ### end Alembic commands ###
