"""add_background_url_to_work_settings

Revision ID: b1d189d65649
Revises: 004_rename_employee_columns
Create Date: 2026-01-07 16:20:31.039014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1d189d65649'
down_revision: Union[str, None] = '004_rename_employee_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.ENUM('CREATE', 'UPDATE', 'DELETE', 'CORRECT', 'REORDER', 'EXPORT'),
               nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=mysql.ENUM('EMPLOYEE', 'ATTENDANCE', 'SETTINGS', 'HOLIDAY', 'DAILY_SCHEDULE', 'ADMIN', 'SERVICE_TYPE', 'SURVEY_QUESTION', 'SURVEY_RESPONSE', 'GUESTBOOK'),
               nullable=False)
    op.alter_column('employees', 'nik',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('employees', 'address',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_employees_nip', table_name='employees')
    op.create_index(op.f('ix_employees_nik'), 'employees', ['nik'], unique=True)
    op.add_column('work_settings', sa.Column('background_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_settings', 'background_url')
    op.drop_index(op.f('ix_employees_nik'), table_name='employees')
    op.create_index('ix_employees_nip', 'employees', ['nik'], unique=True)
    op.alter_column('employees', 'address',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'nik',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=mysql.ENUM('EMPLOYEE', 'ATTENDANCE', 'SETTINGS', 'HOLIDAY', 'DAILY_SCHEDULE', 'ADMIN', 'SERVICE_TYPE', 'SURVEY_QUESTION', 'SURVEY_RESPONSE', 'GUESTBOOK'),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.ENUM('CREATE', 'UPDATE', 'DELETE', 'CORRECT', 'REORDER', 'EXPORT'),
               nullable=True)
    # ### end Alembic commands ###
